name: Run deteKT

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  detekt_check:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: |
            detektAll
            --build-cache
            --continue
            -Pgpr.user=${{ github.actor }}
            -Pgpr.key=${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: build/detekt-sarif-reports/detekt-merged.sarif
      - name: Upload SARIF artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: sarif-reports
          path: "**/build/detekt-sarif-reports/"
          retention-days: 1
